branches:
  only:
    - gh-pages

language: ruby
rvm:
  - 2.1
script:
#  DO NOTHING 
#  The real build happens on the gh-pages branch
#  This file is here to trigger Travis
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
